spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
    #    innoDB?? ??
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    ddl? ????, ???? ????(??)???, ???? ??? ??? ????.
    generate-ddl: true
    hibernate:
      #      create: ?? table? drop? ???
      #      update : entity????? alter? ???? ????? ??.(?? ????? alter?? ?? ??)
      #      validate: ??DDB?? ???? check
      ddl-auto: update
    #      ???? ddl, dml?? ???? ???? ??
    show_sql: true
  #    swagger2.4?? ??? ???? ?? url?? ??? ????
  #    swagger? url : http://localhost:8080/swagger-ui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mapper??(mybatis? ????)? ??? ??. ????? resources ?? ?? scan
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    root: debug